var Solver = require("../Solver")
var solver = new Solver();
console.log(solver.nextOldSolver())
console.log(solver.getNextBestGuess())
solver.guess("arose", "bbgbb")
console.log(solver.nextOldSolver())
console.log(solver.getNextBestGuess())
solver.guess("cloth", "bbgbb")
console.log(solver.nextOldSolver())
console.log(solver.getNextBestGuess())